apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    namespace: user1-gitops
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: base/
    repoURL: https://github.com/duritong/ocp-gitops-app-of-apps
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false

