
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-app
spec:
  destination:
    namespace: user1-simple
    server: https://kubernetes.default.svc
  project: default
  source: 
    path: components/client/base
    repoURL: https://github.com/gitops-examples/simple-app-example/
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false

